const D=LL;const LS={match:"ll-score-match",hole:"ll-score-hole"};const Y={"apple": [361, 531, 152, 387, 388, 505, 340, 194, 423, 428, 330, 376, 367, 168, 558, 390, 165, 562], "bald": [488, 169, 419, 142, 341, 151, 509, 348, 479, 384, 381, 152, 327, 373, 509, 160, 421, 472], "brights": [538, 397, 200, 365, 470, 213, 377, 388, 406, 368, 302, 380, 162, 508, 376, 178, 415, 532]};Object.keys(Y).forEach(k=>D.courses[k].yardages=Y[k]);
const sb=supabase.createClient(D.url,D.key);let M=structuredClone(D.matches),S={},round=1;
const P=id=>D.players.find(p=>p.id===id),C=id=>D.courses[id],names=a=>a.length?a.map(x=>P(x)?.name.split(" ").pop()).join(" / "):"TBD",fn=f=>({high_low:"High / Low",modified_alt:"Modified Alternate Shot",better_ball:"Better Ball",singles:"Singles"}[f]),ch=(id,c)=>P(id)?.[c];
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.view").forEach(x=>x.classList.remove("on"));b.classList.add("on");document.getElementById(b.dataset.v).classList.add("on")});
function strokes(n,si){if(!n)return 0;let q=Math.floor(Math.abs(n)/18),r=Math.abs(n)%18,z=q+(si<=r?1:0);return n<0?-z:z}
function rel(m){let ids=[...m.a,...m.b],v=ids.map(x=>ch(x,m.course)).filter(x=>x!=null),mn=Math.min(...v),o={};ids.forEach(x=>o[x]=ch(x,m.course)==null?null:ch(x,m.course)-mn);return o}
function alt(ids,c){let x=ids.map(i=>ch(i,c));if(x.length!=2||x.some(v=>v==null))return null;x.sort((a,b)=>a-b);return Math.round(.6*x[1]+.4*x[0])}
function get(m,h,id){return S[`${m}:${h}:${id}`]}
function hole(m,h){let si=C(m.course).si[h-1];if(m.format==="modified_alt"){let a=get(m.id,h,"team_a"),b=get(m.id,h,"team_b"),ac=alt(m.a,m.course),bc=alt(m.b,m.course);if([a,b,ac,bc].some(x=>x==null))return null;let mn=Math.min(ac,bc);a-=strokes(ac-mn,si);b-=strokes(bc-mn,si);return a<b?"a":a>b?"b":"h"}let ids=[...m.a,...m.b],r=rel(m);if(ids.some(i=>get(m.id,h,i)==null||r[i]==null))return null;let n={};ids.forEach(i=>n[i]=get(m.id,h,i)-strokes(r[i],si));if(m.format==="singles")return n[m.a[0]]<n[m.b[0]]?"a":n[m.a[0]]>n[m.b[0]]?"b":"h";let a=m.a.map(i=>n[i]).sort((x,y)=>x-y),b=m.b.map(i=>n[i]).sort((x,y)=>x-y);if(m.format==="better_ball")return a[0]<b[0]?"a":a[0]>b[0]?"b":"h";return {low:a[0]<b[0]?"a":a[0]>b[0]?"b":"h",high:a[1]<b[1]?"a":a[1]>b[1]?"b":"h"}}
function state(m){if(!m.a.length||!m.b.length)return{holes:0,label:"Pairings TBD",ap:0,bp:0};let a=0,b=0,h=0;for(let i=1;i<=18;i++){let x=hole(m,i);if(x==null)break;h++;if(m.format==="high_low")[x.low,x.high].forEach(v=>v==="a"?a++:v==="b"?b++:0);else x==="a"?a++:x==="b"?b++:0}let rem=18-h,lead=Math.abs(a-b),available=(m.format==="high_low"?2:1)*rem,done=h===18||lead>available,who=a>b?"Bundrick":b>a?"Dyer":null,label;if(!h)label="Not started";else if(m.format==="high_low")label=`${who?who+" leads":"Tied"} ${a}–${b}`;else label=!who?"All Square":done?`${who} wins ${lead}&${rem}`:`${who} ${lead} UP`;return{holes:h,label,ap:done?(a>b?m.points:a===b?m.points/2:0):0,bp:done?(b>a?m.points:a===b?m.points/2:0):0}}
function livePoints(m){let s=state(m);if(!s.holes)return{a:0,b:0};if(s.ap||s.bp)return{a:s.ap,b:s.bp};let a=0,b=0;for(let i=1;i<=s.holes;i++){let x=hole(m,i);if(m.format==="high_low"){[x.low,x.high].forEach(v=>v==="a"?a++:v==="b"?b++:0)}else x==="a"?a++:x==="b"?b++:0}return a>b?{a:m.points,b:0}:b>a?{a:0,b:m.points}:{a:m.points/2,b:m.points/2}}
function teamClass(s){return s.label.startsWith("Dyer")?"dyer":s.label.startsWith("Bundrick")?"bundrick":""}
function goRound(r){round=r;document.querySelectorAll("nav button,.view").forEach(x=>x.classList.remove("on"));document.querySelector('nav button[data-v="matches"]').classList.add("on");document.getElementById("matches").classList.add("on");render()}
function render(){let ap=0,bp=0;M.forEach(m=>{let p=livePoints(m);ap+=p.a;bp+=p.b});document.getElementById("bp").textContent=ap;document.getElementById("dp").textContent=bp;sessions.innerHTML=[1,2,3,4].map(r=>{let x=M.filter(m=>m.round===r),a=0,b=0,started=false,finished=true;x.forEach(m=>{let p=livePoints(m),st=state(m);a+=p.a;b+=p.b;if(st.holes)started=true;if(!st.ap&&!st.bp)finished=false});let c=C(x[0].course),leader=a>b?"Bundrick":b>a?"Dyer":null,txt=!started?"Not started":finished?(leader?`Team ${leader} won ${Math.max(a,b)}–${Math.min(a,b)}`:`Round tied ${a}–${b}`):(leader?`Team ${leader} leads ${Math.max(a,b)}–${Math.min(a,b)} · LIVE`:`Round tied ${a}–${b} · LIVE`),cl=leader?.toLowerCase()||"";return`<button class="session sessionlink" onclick="goRound(${r})"><div><small>ROUND ${r}</small><h3>${c.name}</h3><span>${fn(x[0].format)}</span></div><b class="${cl}">${txt}</b></button>`}).join("");tabs.innerHTML=[1,2,3,4].map(r=>`<button data-r=${r} class=${r===round?"on":""}>Round ${r}</button>`).join("");tabs.querySelectorAll("button").forEach(b=>b.onclick=()=>{round=+b.dataset.r;render()});cards.innerHTML=M.filter(m=>m.round===round).map(m=>{let st=state(m),cl=teamClass(st);return`<div class=match><small>${C(m.course).name} · ${fn(m.format)} · ${m.points} PT${m.points>1?"S":""}</small><div class=teams><div><b class=bundrick>${names(m.a)}</b></div><i>VS</i><div><b class=dyer>${names(m.b)}</b></div></div><div class=status><span>${st.holes?"Thru "+st.holes:"Not started"}</span><span class="live ${cl}">${st.label}</span></div></div>`}).join("");renderScore();renderPlayers()}
function renderScore(){let ok=M.filter(m=>m.a.length&&m.b.length),cur=sm.value||localStorage.getItem(LS.match);if(!ok.some(m=>m.id===cur))cur=ok[0]?.id||"";sm.innerHTML=ok.map(m=>`<option value=${m.id} ${m.id===cur?"selected":""}>R${m.round}: ${names(m.a)} vs ${names(m.b)}</option>`).join("");sm.value=cur;holeOptions();let saved=+(localStorage.getItem(LS.hole)||1);sh.value=String(Math.min(18,Math.max(1,+sh.value||saved)));fields()}
function fields(){let m=M.find(x=>x.id===sm.value),h=+sh.value;if(!m)return;localStorage.setItem(LS.match,m.id);localStorage.setItem(LS.hole,h);let c=C(m.course);holemeta.textContent=`Par ${c.pars[h-1]} · ${c.yardages[h-1]} yards · Index ${c.si[h-1]}`;inputs.innerHTML=m.format==="modified_alt"?[["team_a",names(m.a),alt(m.a,m.course)],["team_b",names(m.b),alt(m.b,m.course)]].map(x=>`<div class=row><b>${x[1]}<span>Team CH ${x[2]??"—"}</span></b><input data-id=${x[0]} inputmode=numeric type=number value="${get(m.id,h,x[0])??""}"></div>`).join(""):[...m.a,...m.b].map(i=>{let r=rel(m)[i],n=r==null?0:Math.max(0,strokes(r,c.si[h-1])),dots=n?` <strong class=strokedot>${"●".repeat(n)}</strong>`:"";return `<div class=row><b class=${P(i).team.toLowerCase()}>${P(i).name}${dots}<span>CH ${ch(i,m.course)??"—"} · Playing ${r??"—"}</span></b><input data-id=${i} inputmode=numeric type=number value="${get(m.id,h,i)??""}"></div>`}).join("")}
function moveHole(d){sh.value=String(Math.min(18,Math.max(1,(+sh.value||1)+d)));fields()}
sm.onchange=()=>{localStorage.setItem(LS.match,sm.value);holeOptions();sh.value=localStorage.getItem(LS.hole)||"1";fields()};sh.onchange=fields;
save.onclick=async()=>{let m=M.find(x=>x.id===sm.value),h=+sh.value,ii=[...inputs.querySelectorAll("input")];if(ii.some(i=>!i.value))return alert("Enter every score.");let table=m.format==="modified_alt"?"team_hole_scores":"hole_scores",rows=ii.map(i=>m.format==="modified_alt"?{match_id:m.id,hole:h,team:i.dataset.id,gross:+i.value}:{match_id:m.id,hole:h,player_id:i.dataset.id,gross:+i.value});let {error}=await sb.from(table).upsert(rows);if(error)return alert(error.message);rows.forEach(r=>S[`${r.match_id}:${r.hole}:${r.team||r.player_id}`]=r.gross);result.innerHTML=`<div class=card><b>Hole ${h} saved live.</b></div>`;if(h<18)localStorage.setItem(LS.hole,String(h+1));render()}
const HIST={"dyer":[2,"4\u20133","57.1%"],"bundrick":[0,"3\u20135","37.5%"],"shaver":[1,"6\u20131\u20131","75.0%"],"loman":[2,"4\u20134","50.0%"],"miller":[1,"4\u20134","50.0%"],"genett":[1,"1\u20135\u20131","14.3%"],"austin":[0,"2\u20132","50.0%"],"billy":[0,"1\u20132\u20131","25.0%"]};
function renderPlayers(){let cur=document.getElementById("playerselect")?.value||localStorage.getItem("ll-player")||D.players[0].id;pg.innerHTML=`<div class=card><label>Select Player<select id=playerselect>${D.players.map(p=>`<option value="${p.id}" ${p.id===cur?"selected":""}>${p.name}</option>`).join("")}</select></label><div id=profile></div></div>`;playerselect.onchange=()=>{localStorage.setItem("ll-player",playerselect.value);showPlayer(playerselect.value)};showPlayer(cur)}
function showPlayer(id){let p=P(id),h=HIST[id],n=h?.[0]||0;profile.innerHTML=`<div class=champ>🏆 ${n} Lake Lure Championship${n===1?"":"s"}</div><h2>${p.name}</h2><div class=profilegrid><div><small>CURRENT INDEX</small><b>${p.index<0?"+"+Math.abs(p.index):p.index}</b></div><div><small>APPLE</small><b>${p.apple==null?"—":p.apple<0?"+"+Math.abs(p.apple):p.apple}</b></div><div><small>BALD</small><b>${p.bald==null?"—":p.bald<0?"+"+Math.abs(p.bald):p.bald}</b></div><div><small>BRIGHT'S</small><b>${p.brights<0?"+"+Math.abs(p.brights):p.brights}</b></div></div>${h?`<h3>Lake Lure Career</h3><p><b>${h[1]}</b> overall · ${h[2]} win rate</p>`:`<h3>Lake Lure Career</h3><p class=muted>No prior Lake Lure match history.</p>`}<h3>Head-to-Head</h3><p class=muted>Opponent-by-opponent history will be added in the next historical-data pass.</p></div>`}

function opts(team,val){return`<option value="">TBD</option>`+D.players.filter(p=>p.team===team).map(p=>`<option value=${p.id} ${p.id===val?"selected":""}>${p.name}</option>`).join("")}admin.onclick=()=>{modal.classList.add("on");am.innerHTML=M.map(m=>{let n=m.format==="singles"?1:2;return`<div class=adminmatch data-id=${m.id}><b>R${m.round} · ${fn(m.format)}</b><div class=grid>${Array.from({length:n},(_,i)=>`<select data-s=a data-i=${i}>${opts("Bundrick",m.a[i])}</select>`).join("")}${Array.from({length:n},(_,i)=>`<select data-s=b data-i=${i}>${opts("Dyer",m.b[i])}</select>`).join("")}</div></div>`}).join("")};close.onclick=()=>modal.classList.remove("on");
saveAdmin.onclick=async()=>{let rows=[];document.querySelectorAll(".adminmatch").forEach(e=>{let m=M.find(x=>x.id===e.dataset.id),a=[],b=[];e.querySelectorAll("select").forEach(s=>{if(s.value)(s.dataset.s==="a"?a:b)[+s.dataset.i]=s.value});m.a=a.filter(Boolean);m.b=b.filter(Boolean);rows.push({id:m.id,event_id:"lake-lure-2026",round_no:m.round,course_id:m.course,format:m.format,team_a:m.a,team_b:m.b,points:m.points,status:"scheduled"})});let {error}=await sb.from("matches").upsert(rows);if(error)return alert(error.message);modal.classList.remove("on");render()}
async function load(){try{let [a,b,c]=await Promise.all([sb.from("matches").select("*").eq("event_id","lake-lure-2026"),sb.from("hole_scores").select("*"),sb.from("team_hole_scores").select("*")]);if(a.error||b.error||c.error)throw(a.error||b.error||c.error);a.data?.forEach(r=>{let m=M.find(x=>x.id===r.id);if(m){m.a=r.team_a||[];m.b=r.team_b||[]}});b.data?.forEach(r=>S[`${r.match_id}:${r.hole}:${r.player_id}`]=r.gross);c.data?.forEach(r=>S[`${r.match_id}:${r.hole}:${r.team}`]=r.gross);sync.textContent="● Live · Supabase connected";render()}catch(e){sync.textContent="Setup error: "+e.message}}
render();load();sb.channel("live").on("postgres_changes",{event:"*",schema:"public",table:"hole_scores"},load).on("postgres_changes",{event:"*",schema:"public",table:"team_hole_scores"},load).on("postgres_changes",{event:"*",schema:"public",table:"matches"},load).subscribe();