const D=window.LL_DATA;
const baseMatches=[
{id:"apple1",round:"Apple Valley · High/Low",a:["shaver","miller"],b:["dyer","morris"],points:1},
{id:"apple2",round:"Apple Valley · High/Low",a:["loman","fuller"],b:["mark","ayden"],points:1},
{id:"apple3",round:"Apple Valley · High/Low",a:["bundrick","genett"],b:["austin","billy"],points:1}
];
const sessions=[
["Round 1","Apple Valley","High / Low","3 points"],
["Round 2","Bald Mountain","Modified Alternate Shot","3 points"],
["Round 3","Bright's Creek","Better Ball","3 points"],
["Round 4","Bright's Creek","Singles","12 points"]
];
let state=JSON.parse(localStorage.getItem("llstate")||"null")||{scores:{},results:{},players:{},fullerOut:false};
const P=id=>{let p=D.players.find(x=>x.id===id);return {...p,...(state.players[id]||{})}};
const save=()=>localStorage.setItem("llstate",JSON.stringify(state));
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.view).classList.add("active")});
function teamNames(ids){return ids.map(x=>P(x).short).join(" / ")}
function currentMatches(){return baseMatches.map(m=>({...m,a:m.a.map(x=>state.fullerOut&&x==="fuller"?"pratt":x),b:m.b.map(x=>state.fullerOut&&x==="fuller"?"pratt":x)}))}
function renderHome(){document.getElementById("sessionCards").innerHTML=sessions.map((s,i)=>`<div class=session><div><small>${s[0]}</small><h3>${s[1]}</h3><span>${s[2]} · ${s[3]}</span></div><div class=scoreTag>${i? "—":"0–0"}</div></div>`).join(""); updateCup()}
function renderMatches(){document.getElementById("matchCards").innerHTML=currentMatches().map((m,i)=>{let r=calcMatch(m);return `<div class=match><small>MATCH ${i+1}</small><div class=teams><div class=teamSide><b>${teamNames(m.a)}</b><small>Team Bundrick</small></div><div class=vs>VS</div><div class=teamSide><b>${teamNames(m.b)}</b><small>Team Dyer</small></div></div><div class=status><span>${r.holes?`Thru ${r.holes}`:"Not started"}</span><span class="${r.holes?"live":""}">${r.label}</span></div></div>`}).join("")}
function strokeCount(ch,si){if(ch===0)return 0;let sign=ch>0?1:-1,n=Math.abs(ch),base=Math.floor(n/18),rem=n%18;return sign*(base+(si<=rem?1:0))}
function net(g,ch,si){return g-strokeCount(ch,si)}
function calcHole(m,h){let rec=state.scores[m.id]?.[h];if(!rec)return null;let all=[...m.a,...m.b], ch=all.map(id=>P(id).apple), min=Math.min(...ch), rel={};all.forEach(id=>rel[id]=P(id).apple-min);let si=h; // placeholder until official Apple stroke indexes are entered
let ns={};all.forEach(id=>ns[id]=net(rec[id],rel[id],si));
let aVals=m.a.map(id=>ns[id]).sort((x,y)=>x-y),bVals=m.b.map(id=>ns[id]).sort((x,y)=>x-y);
let low=aVals[0]<bVals[0]?"a":aVals[0]>bVals[0]?"b":"h", high=aVals[1]<bVals[1]?"a":aVals[1]>bVals[1]?"b":"h";
return {low,high,ns}}
function calcMatch(m){let a=0,b=0,holes=0;for(let h=1;h<=18;h++){let x=calcHole(m,h);if(!x)continue;holes++;[x.low,x.high].forEach(y=>{if(y==="a")a+=.5;if(y==="b")b+=.5})}let diff=b-a,label=holes?(diff>0?`Dyer +${diff}`:diff<0?`Bundrick +${-diff}`:"All Square"):"Not started";return {a,b,holes,label}}
function renderScore(){let ms=currentMatches(),sel=document.getElementById("scoreMatch");sel.innerHTML=ms.map((m,i)=>`<option value=${m.id}>Match ${i+1}: ${teamNames(m.a)} vs ${teamNames(m.b)}</option>`).join("");let hs=document.getElementById("scoreHole");hs.innerHTML=Array.from({length:18},(_,i)=>`<option>${i+1}</option>`).join("");sel.onchange=scoreFields;hs.onchange=scoreFields;scoreFields()}
function scoreFields(){let m=currentMatches().find(x=>x.id===document.getElementById("scoreMatch").value),h=+document.getElementById("scoreHole").value,rec=state.scores[m.id]?.[h]||{};document.getElementById("scoreInputs").innerHTML=[...m.a,...m.b].map(id=>`<div class=scoreRow><b>${P(id).name}<span>Apple CH ${fmt(P(id).apple)}</span></b><input type=number min=1 max=15 data-id=${id} value="${rec[id]||""}" placeholder="Gross"></div>`).join("")}
document.getElementById("saveScores").onclick=()=>{let m=currentMatches().find(x=>x.id===document.getElementById("scoreMatch").value),h=+document.getElementById("scoreHole").value;state.scores[m.id]??={};state.scores[m.id][h]={};document.querySelectorAll("#scoreInputs input").forEach(x=>state.scores[m.id][h][x.dataset.id]=+x.value);save();let x=calcHole(m,h);document.getElementById("holeResult").innerHTML=x?`<div class=panel><b>Hole ${h} saved.</b><p class=hint>Low: ${x.low==="a"?"Bundrick":x.low==="b"?"Dyer":"Halved"} · High: ${x.high==="a"?"Bundrick":x.high==="b"?"Dyer":"Halved"}</p></div>`:"";renderMatches();updateCup()}
function fmt(n){if(n==null)return"—";return n<0?`+${Math.abs(n)}`:`${n}`}
function renderPlayers(q=""){let arr=D.players.filter(p=>!p.sub||["pratt","haneline"].includes(p.id)).filter(p=>p.name.toLowerCase().includes(q.toLowerCase()));document.getElementById("playerGrid").innerHTML=arr.map(p=>{p=P(p.id);let h=D.history[p.short]||{},gp=(h.w||0)+(h.l||0)+(h.h||0);return `<div class=player><div style="display:flex;justify-content:space-between"><div><h3>${p.name}</h3><small>${p.team==="Alumni"?"Alumni / reserve":"Team "+p.team}${p.sub?" · reserve":""}</small></div><div class=idx>${fmt(p.index)}</div></div><div class=mini><div><b>${fmt(p.apple)}</b><span>APPLE CH</span></div><div><b>${fmt(p.bald)}</b><span>BALD CH</span></div><div><b>${fmt(p.brights)}</b><span>BRIGHT'S CH</span></div></div><div class=record>${gp?`<b>${h.w}-${h.l}${h.h?`-${h.h}`:""}</b> Lake Lure · ${h.pts} pts<br>Singles ${h.singles} · Best Ball ${h.best} · Mod Alt ${h.mod} · High/Low ${h.high}<br>Bright's ${h.brights} · Apple ${h.apple} · Bald ${h.bald}`:"No prior Lake Lure match history."}</div><a href="${p.ghin}" target=_blank style="font-size:11px;color:#1e5b43">GHIN profile ↗</a></div>`}).join("")}
document.getElementById("playerSearch").oninput=e=>renderPlayers(e.target.value);
function renderWeekend(){let f=state.fullerOut?"Pratt":"Fuller";document.getElementById("weekendCard").innerHTML=`<div class=weekcard><small>FRIDAY · APPLE VALLEY</small><h3>High / Low</h3><div class=pair><span>Shaver / Miller</span><b>Dyer / Morris</b></div><div class=pair><span>Loman / ${f}</span><b>Mark / Ayden</b></div><div class=pair><span>Bundrick / Genett</span><b>Austin / Billy</b></div></div><div class=weekcard><small>SATURDAY · BALD MOUNTAIN</small><h3>Modified Alternate Shot</h3><div class=pair><span>Bundrick pairings TBD</span><b>Austin / Ayden</b></div><div class=pair><span>Bundrick pairings TBD</span><b>Morris / Billy</b></div><div class=pair><span>Bundrick pairings TBD</span><b>Dyer / Mark</b></div></div><div class=weekcard><small>SATURDAY · BRIGHT'S CREEK</small><h3>Better Ball</h3><div class=pair><span>Bundrick pairings TBD</span><b>Morris / Ayden</b></div><div class=pair><span>Bundrick pairings TBD</span><b>Billy / Dyer</b></div><div class=pair><span>Bundrick pairings TBD</span><b>Austin / Mark</b></div></div><div class=weekcard><small>SUNDAY · BRIGHT'S CREEK</small><h3>Singles · 2 points each</h3><div class=pair><span>Shaver</span><b>Austin</b></div><div class=pair><span>Loman</span><b>Mark</b></div><div class=pair><span>Other matchups</span><b>TBD</b></div></div>`}
function updateCup(){let b=0,d=0;currentMatches().forEach(m=>{let r=calcMatch(m);if(r.holes===18){if(r.a>r.b)b++;else if(r.b>r.a)d++;else{b+=.5;d+=.5}}});document.getElementById("bundrickPts").textContent=b;document.getElementById("dyerPts").textContent=d}
document.getElementById("adminBtn").onclick=()=>{document.getElementById("modal").classList.add("open");renderAdmin()}
document.getElementById("closeModal").onclick=()=>document.getElementById("modal").classList.remove("open");
function renderAdmin(){let core=D.players.filter(p=>p.team!=="Alumni");document.getElementById("adminPlayers").innerHTML=`<label style="display:block;margin:10px 0"><input id=fullerOut type=checkbox ${state.fullerOut?"checked":""}> Fuller out — use Nate Pratt</label><div class=adminRow style="font-weight:bold"><span>Player</span><span>Index</span><span>Apple</span><span>Bald</span><span>Bright's</span></div>`+core.map(p=>{p=P(p.id);return `<div class=adminRow data-p=${p.id}><span>${p.short}${p.sub?` <i class=subnote>SUB</i>`:""}</span><input data-k=index value="${p.index??""}"><input data-k=apple value="${p.apple??""}"><input data-k=bald value="${p.bald??""}"><input data-k=brights value="${p.brights??""}"></div>`}).join("")}
document.getElementById("saveAdmin").onclick=()=>{state.fullerOut=document.getElementById("fullerOut").checked;document.querySelectorAll(".adminRow[data-p]").forEach(r=>{state.players[r.dataset.p]??={};r.querySelectorAll("input").forEach(i=>state.players[r.dataset.p][i.dataset.k]=i.value===""?null:+i.value)});save();document.getElementById("modal").classList.remove("open");renderAll()}
function renderAll(){renderHome();renderMatches();renderScore();renderPlayers();renderWeekend()}
renderAll();