const D=LL;const LS={match:"ll-score-match",hole:"ll-score-hole",view:"ll-view",round:"ll-round",player:"ll-player"};const ADMIN_PIN="2527";if(!D.players.some(p=>p.id==="brown"))D.players.push({id:"brown",name:"Justin Brown",team:"Bundrick",index:0.1,apple:null,bald:null,brights:1,ghin:"https://www.ghin.com/golfer-lookup/golfer/53616c7465645f5f15b96889a4af0e8c1e05ad4246793204/club/28469",sub:true});const Y={"apple": [361, 531, 152, 387, 388, 505, 340, 194, 423, 428, 330, 376, 367, 168, 558, 390, 165, 562], "bald": [488, 169, 419, 142, 341, 151, 509, 348, 479, 384, 381, 152, 327, 373, 509, 160, 421, 472], "brights": [538, 397, 200, 365, 470, 213, 377, 388, 406, 368, 302, 380, 162, 508, 376, 178, 415, 532]};Object.keys(Y).forEach(k=>D.courses[k].yardages=Y[k]);
const sb=supabase.createClient(D.url,D.key);const HKEY="ll-handicap-snapshot-2026";let HS=JSON.parse(localStorage.getItem(HKEY)||"{}");D.players.forEach(p=>{if(HS[p.id])Object.assign(p,HS[p.id])});let M=structuredClone(D.matches),S={},round=+(localStorage.getItem(LS.round)||1);
const P=id=>D.players.find(p=>p.id===id),C=id=>D.courses[id],names=a=>a.length?a.map(x=>P(x)?.name.split(" ").pop()).join(" / "):"TBD",fn=f=>({high_low:"High / Low",modified_alt:"Modified Alternate Shot",better_ball:"Better Ball",singles:"Singles"}[f]),ch=(id,c)=>P(id)?.[c];
function showView(v){document.querySelectorAll("nav button,.view").forEach(x=>x.classList.remove("on"));document.querySelector(`nav button[data-v="${v}"]`)?.classList.add("on");document.getElementById(v)?.classList.add("on");localStorage.setItem(LS.view,v)}document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>showView(b.dataset.v));
function strokes(n,si){if(!n)return 0;let q=Math.floor(Math.abs(n)/18),r=Math.abs(n)%18,z=q+(si<=r?1:0);return n<0?-z:z}
function rel(m){let ids=[...m.a,...m.b],v=ids.map(x=>ch(x,m.course)).filter(x=>x!=null),mn=Math.min(...v),o={};ids.forEach(x=>o[x]=ch(x,m.course)==null?null:ch(x,m.course)-mn);return o}
function calcCH(index,cid){let c=C(cid),par=c.pars.reduce((a,b)=>a+b,0);return Math.round(index*(c.slope/113)+(c.rating-par))}function saveHandicapSnapshot(){let z={};D.players.forEach(p=>z[p.id]={index:p.index,apple:p.apple,bald:p.bald,brights:p.brights});localStorage.setItem(HKEY,JSON.stringify(z))}function alt(ids,c){let x=ids.map(i=>ch(i,c));if(x.length!=2||x.some(v=>v==null))return null;x.sort((a,b)=>a-b);return Math.round(.6*x[1]+.4*x[0])}
function get(m,h,id){return S[`${m}:${h}:${id}`]}
function hole(m,h){let si=C(m.course).si[h-1];if(m.format==="modified_alt"){let a=get(m.id,h,"team_a"),b=get(m.id,h,"team_b"),ac=alt(m.a,m.course),bc=alt(m.b,m.course);if([a,b,ac,bc].some(x=>x==null))return null;let mn=Math.min(ac,bc);a-=strokes(ac-mn,si);b-=strokes(bc-mn,si);return a<b?"a":a>b?"b":"h"}let ids=[...m.a,...m.b],r=rel(m);if(ids.some(i=>get(m.id,h,i)==null||r[i]==null))return null;let n={};ids.forEach(i=>n[i]=get(m.id,h,i)-strokes(r[i],si));if(m.format==="singles")return n[m.a[0]]<n[m.b[0]]?"a":n[m.a[0]]>n[m.b[0]]?"b":"h";let a=m.a.map(i=>n[i]).sort((x,y)=>x-y),b=m.b.map(i=>n[i]).sort((x,y)=>x-y);if(m.format==="better_ball")return a[0]<b[0]?"a":a[0]>b[0]?"b":"h";return {low:a[0]<b[0]?"a":a[0]>b[0]?"b":"h",high:a[1]<b[1]?"a":a[1]>b[1]?"b":"h"}}
function sideName(m,side){return names(side==="a"?m.a:m.b)}
function state(m){if(!m.a.length||!m.b.length)return{holes:0,label:"Pairings TBD",ap:0,bp:0,side:null,done:false};let a=0,b=0,h=0;for(let i=1;i<=18;i++){let x=hole(m,i);if(x==null)break;h++;if(m.format==="high_low")[x.low,x.high].forEach(v=>v==="a"?a++:v==="b"?b++:0);else x==="a"?a++:x==="b"?b++:0}let rem=18-h,lead=Math.abs(a-b),available=(m.format==="high_low"?2:1)*rem,done=h===18||lead>available,side=a>b?"a":b>a?"b":null,label;if(!h)label="Not started";else if(done){if(!side)label=m.format==="high_low"?`HALVED ${a}–${b}`:"HALVED";else if(m.format==="high_low")label=`${sideName(m,side)} WIN ${Math.max(a,b)}–${Math.min(a,b)}`;else label=rem?`${sideName(m,side)} ${lead} & ${rem}`:`${sideName(m,side)} ${lead} UP`}else if(!side)label=m.format==="high_low"?`AS · ${a}–${b}`:"AS";else if(m.format==="high_low")label=`${sideName(m,side)} LEAD ${Math.max(a,b)}–${Math.min(a,b)}`;else label=`${lead===rem&&rem>0?"DORMIE · ":""}${sideName(m,side)} ${lead} UP`;return{holes:h,label,ap:done?(a>b?m.points:a===b?m.points/2:0):0,bp:done?(b>a?m.points:a===b?m.points/2:0):0,side,done}}
function livePoints(m){let s=state(m);if(!s.holes)return{a:0,b:0};if(s.done)return{a:s.ap,b:s.bp};let a=0,b=0;for(let i=1;i<=s.holes;i++){let x=hole(m,i);if(m.format==="high_low"){[x.low,x.high].forEach(v=>v==="a"?a++:v==="b"?b++:0)}else x==="a"?a++:x==="b"?b++:0}return a>b?{a:m.points,b:0}:b>a?{a:0,b:m.points}:{a:m.points/2,b:m.points/2}}
function teamClass(s){return s.side==="b"?"dyer":s.side==="a"?"bundrick":""}
const ROUNDINFO={1:{day:"FRI",date:"2026-09-25",lat:35.459,lng:-82.184},2:{day:"SAT",date:"2026-09-26",lat:35.459,lng:-82.184},3:{day:"SAT",date:"2026-09-26",lat:35.258,lng:-82.207},4:{day:"SUN",date:"2026-09-27",lat:35.258,lng:-82.207}};
function statusText(m,st=state(m)){return `${st.holes&&!st.done?`THRU ${st.holes} · `:""}${st.label.toUpperCase()}`}
function statusClass(st){return st.side==="a"?"lead-bundrick":st.side==="b"?"lead-dyer":"neutral"}
function firstIncomplete(m){for(let h=1;h<=18;h++)if(hole(m,h)==null)return h;return 18}
function renderScoreStatus(){let m=M.find(x=>x.id===sm.value);if(!m||!window.scoreStatus)return;let st=state(m);scoreStatus.className=`scorestatus ${statusClass(st)}`;scoreStatus.textContent=statusText(m,st)}
function roundIntro(r){let k=`ll-round-intro-${r}`;if(sessionStorage.getItem(k))return;let x=M.find(m=>m.round===r);if(!x)return;roundIntroText.innerHTML=`<strong>ROUND ${r}</strong><b>${C(x.course).name.toUpperCase()}</b><span>${fn(x.format).toUpperCase()}</span>`;roundIntro.classList.add("on");sessionStorage.setItem(k,"1");setTimeout(()=>roundIntro.classList.remove("on"),1900)}
async function weatherForRound(r){let w=document.getElementById("weather"),ri=ROUNDINFO[r],m=M.find(x=>x.round===r);if(!w||!ri||!m)return;w.innerHTML=`<b>${ri.day} · ${C(m.course).name.toUpperCase()}</b><small>Loading weather…</small>`;try{let u=`https://api.open-meteo.com/v1/forecast?latitude=${ri.lat}&longitude=${ri.lng}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m,wind_direction_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=America%2FNew_York&forecast_days=10`;let j=await fetch(u).then(x=>{if(!x.ok)throw Error("weather unavailable");return x.json()}),today=new Date().toLocaleDateString("en-CA",{timeZone:"America/New_York"}),idx=j.daily.time.indexOf(ri.date),isToday=today===ri.date,dir=d=>["N","NE","E","SE","S","SW","W","NW"][Math.round(d/45)%8];if(isToday&&j.current){w.innerHTML=`<span class=wxmain>${ri.day} · ${C(m.course).name.toUpperCase()} · ${Math.round(j.current.temperature_2m)}°</span><span class=wxmeta>Feels ${Math.round(j.current.apparent_temperature)}° · ${dir(j.current.wind_direction_10m)} ${Math.round(j.current.wind_speed_10m)} mph${idx>=0?` · Rain ${j.daily.precipitation_probability_max[idx]??0}%`:""}</span>`}else if(idx>=0){w.innerHTML=`<span class=wxmain>${ri.day} · ${C(m.course).name.toUpperCase()} · ${Math.round(j.daily.temperature_2m_min[idx])}–${Math.round(j.daily.temperature_2m_max[idx])}°</span><span class=wxmeta>Rain ${j.daily.precipitation_probability_max[idx]??0}%</span>`}else throw Error("forecast not in range")}catch(e){w.innerHTML=`<b>${ri.day} · ${C(m.course).name.toUpperCase()}</b><small>Weather temporarily unavailable</small>`}}
function goRound(r){round=r;localStorage.setItem(LS.round,String(r));showView("matches");render();roundIntro(r);weatherForRound(r)}
function render(){let pa=0,pb=0,sa=0,sb2=0;M.forEach(m=>{let p=livePoints(m),st=state(m);pa+=p.a;pb+=p.b;sa+=st.ap;sb2+=st.bp});document.getElementById("bp").textContent=pa;document.getElementById("dp").textContent=pb;document.getElementById("bs").textContent=sa;document.getElementById("ds").textContent=sb2;sessions.innerHTML=[1,2,3,4].map(r=>{let x=M.filter(m=>m.round===r),a=0,b=0,started=false,finished=true;x.forEach(m=>{let p=livePoints(m),st=state(m);a+=p.a;b+=p.b;if(st.holes)started=true;if(!st.done)finished=false});let c=C(x[0].course),leader=a>b?"Bundrick":b>a?"Dyer":null,txt=!started?"Not started":finished?(leader?`Team ${leader} won ${Math.max(a,b)}–${Math.min(a,b)}`:`Round tied ${a}–${b}`):(leader?`Team ${leader} leads ${Math.max(a,b)}–${Math.min(a,b)}`:`Round tied ${a}–${b}`),cl=leader?.toLowerCase()||"";return`<button class="session sessionlink" onclick="goRound(${r})"><div><small>ROUND ${r}</small><h3>${c.name}</h3><span>${fn(x[0].format)}</span></div><b class="${cl}">${txt}</b></button>`}).join("");tabs.innerHTML=[1,2,3,4].map(r=>`<button data-r=${r} class=${r===round?"on":""}>Round ${r}</button>`).join("");tabs.querySelectorAll("button").forEach(b=>b.onclick=()=>{round=+b.dataset.r;localStorage.setItem(LS.round,String(round));render();roundIntro(round)});cards.innerHTML=M.filter(m=>m.round===round).map(m=>{let st=state(m),cl=statusClass(st);return`<div class="match clickable" onclick="openScorecard('${m.id}')"><small>${C(m.course).name} · ${fn(m.format)} · ${m.points} PT${m.points>1?"S":""}</small><div class=teams><div><b class=bundrick>${names(m.a)}</b></div><i>VS</i><div><b class=dyer>${names(m.b)}</b></div></div><div class="status ${cl}"><span>${statusText(m,st)}</span></div></div>`}).join("");weatherForRound(round);let prevA=+(localStorage.getItem("ll-seen-secured-a")||0),prevB=+(localStorage.getItem("ll-seen-secured-b")||0);if(document.getElementById("cup").classList.contains("on")){if(sa>prevA){bs.classList.remove("pointpulse");void bs.offsetWidth;bs.classList.add("pointpulse")}if(sb2>prevB){ds.classList.remove("pointpulse");void ds.offsetWidth;ds.classList.add("pointpulse")}localStorage.setItem("ll-seen-secured-a",sa);localStorage.setItem("ll-seen-secured-b",sb2)}renderScore();renderPlayers()}
function holeOptions(){let m=M.find(x=>x.id===sm.value);if(!m){sh.innerHTML="";return}let c=C(m.course),cur=+(localStorage.getItem(LS.hole)||sh.value||1);sh.innerHTML=Array.from({length:18},(_,i)=>{let h=i+1;return `<option value="${h}">${h} · Par ${c.pars[i]} · ${c.yardages[i]} yds · Index ${c.si[i]}</option>`}).join("");sh.value=String(Math.min(18,Math.max(1,cur)))}
function renderScore(){let ok=M.filter(m=>m.a.length&&m.b.length),cur=localStorage.getItem(LS.match)||sm.value;if(!ok.some(m=>m.id===cur))cur=ok[0]?.id||"";sm.innerHTML=ok.map(m=>`<option value=${m.id} ${m.id===cur?"selected":""}>R${m.round}: ${names(m.a)} vs ${names(m.b)}</option>`).join("");sm.value=cur;let saved=+(localStorage.getItem(LS.hole)||1);if(saved<1||saved>18)saved=1;sh.value=String(saved);holeOptions();sh.value=String(saved);fields()}
function fields(){let m=M.find(x=>x.id===sm.value),h=+sh.value;if(!m||!Number.isInteger(h)||h<1||h>18)return;renderScoreStatus();localStorage.setItem(LS.match,m.id);localStorage.setItem(LS.hole,h);let c=C(m.course);inputs.innerHTML=m.format==="modified_alt"?[["team_a",names(m.a),alt(m.a,m.course)],["team_b",names(m.b),alt(m.b,m.course)]].map(x=>`<div class=row><b>${x[1]}<span>Team CH ${x[2]??"—"}</span></b><div class=scorecell><input data-id=${x[0]} inputmode=numeric type=number value="${get(m.id,h,x[0])??""}"></div></div>`).join(""):[...m.a,...m.b].map(i=>{let r=rel(m)[i],n=r==null?0:Math.max(0,strokes(r,c.si[h-1])),dots=n?`<strong class=strokedot aria-label="${n} stroke${n>1?"s":""}">${"●".repeat(n)}</strong>`:`<strong class="strokedot empty"></strong>`;return `<div class=row><b class=${P(i).team.toLowerCase()}>${P(i).name}<span>CH ${ch(i,m.course)??"—"} · Playing ${r??"—"}</span></b><div class=scorecell>${dots}<input data-id=${i} inputmode=numeric type=number value="${get(m.id,h,i)??""}"></div></div>`}).join("")}
function moveHole(d){let h=+sh.value||1;h=Math.min(18,Math.max(1,h+d));sh.value=String(h);localStorage.setItem(LS.hole,String(h));fields()}
sm.onchange=()=>{localStorage.setItem(LS.match,sm.value);let m=M.find(x=>x.id===sm.value),h=m?firstIncomplete(m):1;localStorage.setItem(LS.hole,String(h));sh.value=String(h);holeOptions();sh.value=String(h);fields()};sh.onchange=()=>{localStorage.setItem(LS.hole,sh.value);fields()};
save.onclick=async()=>{let m=M.find(x=>x.id===sm.value),h=+sh.value;if(!Number.isInteger(h)||h<1||h>18)return alert("Please select a valid hole from 1–18.");let ii=[...inputs.querySelectorAll("input")],isAlt=m.format==="modified_alt",table=isAlt?"team_hole_scores":"hole_scores",entered=[],deleted=[];ii.forEach(i=>{let key=`${m.id}:${h}:${i.dataset.id}`,had=S[key]!=null,val=i.value.trim();if(val!=="")entered.push(isAlt?{match_id:m.id,hole:h,team:i.dataset.id,gross:+val}:{match_id:m.id,hole:h,player_id:i.dataset.id,gross:+val});else if(had)deleted.push(i.dataset.id)});if(!entered.length&&!deleted.length)return alert("Enter at least one score, or clear a previously saved score to delete it.");if(deleted.length&&!confirm(`Delete ${deleted.length} saved score${deleted.length>1?"s":""} from Hole ${h}?`)){fields();return}let err=null;if(entered.length){let q=await sb.from(table).upsert(entered);err=q.error}if(!err&&deleted.length){let q=sb.from(table).delete().eq("match_id",m.id).eq("hole",h);q=isAlt?q.in("team",deleted):q.in("player_id",deleted);let d=await q;err=d.error}if(err)return alert(err.message);entered.forEach(r=>S[`${r.match_id}:${r.hole}:${r.team||r.player_id}`]=r.gross);deleted.forEach(id=>delete S[`${m.id}:${h}:${id}`]);let complete=hole(m,h)!=null;result.innerHTML=`<div class=card><b>Hole ${h} updated live.</b>${complete?"":`<p class=muted>Partial scores saved. Stay on this hole to add the remaining scores.</p>`}</div>`;if(complete&&h<18){localStorage.setItem(LS.hole,String(h+1));sh.value=String(h+1)}render()}
const TITLES={dyer:2,loman:2,haneline:1,genett:1,shaver:1,miller:1};
const HM=[
{y:2024,f:"high_low",c:"bald",a:["shaver","miller"],b:["dyer","genett"],w:"a"},{y:2024,f:"high_low",c:"bald",a:["bundrick","billy"],b:["haneline","loman"],w:"b"},{y:2024,f:"quota",c:"apple",a:["shaver","billy"],b:["haneline","genett"],w:"h"},{y:2024,f:"quota",c:"apple",a:["bundrick","miller"],b:["dyer","loman"],w:"b"},{y:2024,f:"better_ball",c:"brights",a:["shaver","bundrick"],b:["genett","loman"],w:"a"},{y:2024,f:"better_ball",c:"brights",a:["billy","miller"],b:["dyer","haneline"],w:"b"},{y:2024,f:"singles",c:"brights",a:["shaver"],b:["haneline"],w:"b"},{y:2024,f:"singles",c:"brights",a:["billy"],b:["dyer"],w:"a"},{y:2024,f:"singles",c:"brights",a:["bundrick"],b:["loman"],w:"a"},{y:2024,f:"singles",c:"brights",a:["miller"],b:["genett"],w:"b"},
{y:2025,f:"vegas",c:"apple",a:["austin","genett"],b:["shaver","dyer"],w:"b"},{y:2025,f:"vegas",c:"apple",a:["bundrick","eskew"],b:["miller","loman"],w:"b"},{y:2025,f:"modified_alt",c:"bald",a:["austin","bundrick"],b:["shaver","loman"],w:"b"},{y:2025,f:"modified_alt",c:"bald",a:["eskew","genett"],b:["dyer","miller"],w:"b"},{y:2025,f:"better_ball",c:"brights",a:["bundrick","genett"],b:["shaver","miller"],w:"b"},{y:2025,f:"better_ball",c:"brights",a:["austin","eskew"],b:["dyer","loman"],w:"a"},{y:2025,f:"singles",c:"brights",a:["austin"],b:["miller"],w:"a"},{y:2025,f:"singles",c:"brights",a:["eskew"],b:["shaver"],w:"b"},{y:2025,f:"singles",c:"brights",a:["bundrick"],b:["loman"],w:"a"}];
const HN={haneline:"Matt Haneline",eskew:"Eskew"};
function rec(id,filter=()=>true){let w=0,l=0,h=0;HM.filter(filter).forEach(m=>{let side=m.a.includes(id)?"a":m.b.includes(id)?"b":null;if(!side)return;if(m.w==="h")h++;else if(m.w===side)w++;else l++});return{w,l,h,n:w+l+h}}
function recText(r){return r.n?`${r.w}–${r.l}${r.h?`–${r.h}`:""}`:"—"}function pct(r){return r.n?`${(100*r.w/r.n).toFixed(1)}%`:"—"}function histName(id){return P(id)?.name||HN[id]||id}
function h2h(id){let z={};HM.forEach(m=>{let side=m.a.includes(id)?"a":m.b.includes(id)?"b":null;if(!side)return;(side==="a"?m.b:m.a).forEach(o=>{z[o]??={w:0,l:0,h:0,n:0};z[o].n++;if(m.w==="h")z[o].h++;else if(m.w===side)z[o].w++;else z[o].l++})});return z}
function statRows(id,items,filter){return items.map(([k,label])=>{let r=rec(id,m=>filter(m,k));return `<div class=statrow><span>${label}</span><b>${recText(r)}</b><small>${pct(r)}</small></div>`}).join("")}
function renderPlayers(){let cur=document.getElementById("playerselect")?.value||localStorage.getItem(LS.player)||D.players[0].id;pg.innerHTML=`<div class=card><label>Select Player<select id=playerselect>${D.players.map(p=>`<option value="${p.id}" ${p.id===cur?"selected":""}>${p.name}</option>`).join("")}</select></label><div id=profile></div></div>`;playerselect.onchange=()=>{localStorage.setItem(LS.player,playerselect.value);showPlayer(playerselect.value)};showPlayer(cur)}
function showPlayer(id){let p=P(id),r=rec(id),n=TITLES[id]||0,formats=[["singles","Singles"],["high_low","High / Low"],["better_ball","Better Ball"],["modified_alt","Modified Alt Shot"],["quota","Quota"],["vegas","Vegas"]],courses=[["apple","Apple Valley"],["bald","Bald Mountain"],["brights","Bright's Creek"]],years=[[2024,"2024"],[2025,"2025"]],hh=h2h(id),hhrows=Object.entries(hh).sort((a,b)=>histName(a[0]).localeCompare(histName(b[0]))).map(([o,x])=>`<div class=statrow><span>${histName(o)}</span><b>${recText(x)}</b><small>${pct(x)}</small></div>`).join("");profile.innerHTML=`<div class=champ>🏆 ${n} Lake Lure Championship${n===1?"":"s"}</div><h2>${p.name}</h2><div class=profilegrid><div><small>CURRENT INDEX</small><b>${p.index==null?"—":p.index<0?"+"+Math.abs(p.index):p.index}</b></div><div><small>APPLE</small><b>${p.apple==null?"—":p.apple<0?"+"+Math.abs(p.apple):p.apple}</b></div><div><small>BALD</small><b>${p.bald==null?"—":p.bald<0?"+"+Math.abs(p.bald):p.bald}</b></div><div><small>BRIGHT'S</small><b>${p.brights==null?"—":p.brights<0?"+"+Math.abs(p.brights):p.brights}</b></div></div><h3>Lake Lure Career</h3><div class=careerbig><b>${recText(r)}</b><span>${pct(r)} win rate</span></div><div class=histgrid><div><h3>By Format</h3>${statRows(id,formats,(m,k)=>m.f===k)}</div><div><h3>By Course</h3>${statRows(id,courses,(m,k)=>m.c===k)}</div><div><h3>By Year</h3>${statRows(id,years,(m,k)=>m.y===k)}</div></div><h3>Head-to-Head</h3>${hhrows||`<p class=muted>No prior Lake Lure match history.</p>`}<p class=muted>2025 Genett singles DNP is excluded from all records.</p>`}
function netFor(m,h,id){let g=get(m.id,h,id);if(g==null)return"—";let r=rel(m)[id],si=C(m.course).si[h-1];return r==null?g:g-strokes(r,si)}
function scoreMark(g,par){if(g==null)return"—";let d=g-par,cl=d<=-2?"eaglemark":d===-1?"birdiemark":d===1?"bogeymark":d>=2?"doublebogeymark":"";return cl?`<span class="gmark ${cl}">${g}</span>`:`<span class="gmark">${g}</span>`}
function segmentTotal(m,id,a,b){let vals=[];for(let h=a;h<=b;h++){let v=get(m.id,h,id);if(v!=null)vals.push(+v)}return vals.length?vals.reduce((x,y)=>x+y,0):"—"}
function totalRow(m,label,a,b,keys){let vals=keys.map(k=>segmentTotal(m,k,a,b));return`<tr class="totalrow"><th>${label}</th>${vals.map(v=>`<td><b>${v}</b></td>`).join("")}<td></td></tr>`}
function openScorecard(id){let m=M.find(x=>x.id===id);if(!m)return;let c=C(m.course),st=state(m),ids=[...m.a,...m.b],keys=m.format==="modified_alt"?["team_a","team_b"]:ids;scTitle.textContent=`R${m.round} · ${names(m.a)} vs ${names(m.b)}`;scSub.textContent=`${c.name} · ${fn(m.format)} · ${st.label}${st.holes&&!st.done?` · Thru ${st.holes}`:""}`;let heads=m.format==="modified_alt"?[names(m.a),names(m.b)]:ids.map(i=>P(i).name.split(" ").pop()),rows="";for(let i=0;i<18;i++){let h=i+1,si=c.si[i],cells;if(m.format==="modified_alt")cells=keys.map(k=>{let g=get(m.id,h,k);return g==null?"—":scoreMark(g,c.pars[i])});else cells=ids.map(pid=>{let g=get(m.id,h,pid);if(g==null)return"—";let r=rel(m)[pid],n=Math.max(0,strokes(r,si)),net=netFor(m,h,pid);return `${scoreMark(g,c.pars[i])}${n?`<span class="scdot">${"●".repeat(n)}</span>`:""}<small>${net}</small>`});let hr=hole(m,h),res="—";if(hr!=null){if(m.format==="high_low")res=`<span class="hlres">Low: <b class="${hr.low==="a"?"bundrick":hr.low==="b"?"dyer":""}">${hr.low==="a"?"Bundrick":hr.low==="b"?"Dyer":"Tied"}</b><br>High: <b class="${hr.high==="a"?"bundrick":hr.high==="b"?"dyer":""}">${hr.high==="a"?"Bundrick":hr.high==="b"?"Dyer":"Tied"}</b></span>`;else res=hr==="a"?"B":hr==="b"?"D":"T"}rows+=`<tr><th>${h}<small>P${c.pars[i]} · ${si}</small></th>${cells.map(x=>`<td>${x}</td>`).join("")}<td class=resultcell>${res}</td></tr>`;if(h===9)rows+=totalRow(m,"OUT",1,9,keys);if(h===18){rows+=totalRow(m,"IN",10,18,keys);rows+=totalRow(m,"TOTAL",1,18,keys)}}scTable.innerHTML=`<thead><tr><th>Hole</th>${heads.map(x=>`<th>${x}</th>`).join("")}<th>Result</th></tr></thead><tbody>${rows}</tbody>`;scEdit.onclick=()=>{scorecard.classList.remove("on");localStorage.setItem(LS.match,m.id);localStorage.setItem(LS.hole,String(Math.min(18,st.holes+1||1)));showView("score");renderScore()};scorecard.classList.add("on")}
document.getElementById("scClose").onclick=()=>scorecard.classList.remove("on");scorecard.addEventListener("click",e=>{if(e.target===scorecard)scorecard.classList.remove("on")});
function opts(team,val){return`<option value="">TBD</option>`+D.players.filter(p=>p.team===team).map(p=>`<option value=${p.id} ${p.id===val?"selected":""}>${p.name}${p.sub?" · SUB":""}</option>`).join("")}
function renderAdminPairings(){am.innerHTML=M.map(m=>{let n=m.format==="singles"?1:2;return`<div class=adminmatch data-id=${m.id}><b>R${m.round} · ${fn(m.format)}</b><div class=grid>${Array.from({length:n},(_,i)=>`<select data-s=a data-i=${i}>${opts("Bundrick",m.a[i])}</select>`).join("")}${Array.from({length:n},(_,i)=>`<select data-s=b data-i=${i}>${opts("Dyer",m.b[i])}</select>`).join("")}</div></div>`}).join("")}
function renderAdminHandicaps(){am.innerHTML=`<p class=muted>Enter a current index. Course handicaps preview automatically before saving.</p>`+D.players.map(p=>`<div class="handicaprow" data-p="${p.id}"><div><b>${p.name}</b><small>${p.team}${p.sub?" · SUB":""}</small></div><input class=hindex type=number step=.1 inputmode=decimal value="${p.index??""}"><div class=hcalc>Apple ${p.apple??"—"} · Bald ${p.bald??"—"} · Bright's ${p.brights??"—"}</div></div>`).join("");am.querySelectorAll(".hindex").forEach(i=>i.oninput=()=>{let row=i.closest(".handicaprow"),v=parseFloat(i.value);row.querySelector(".hcalc").textContent=Number.isNaN(v)?"Enter an index":`Apple ${calcCH(v,"apple")} · Bald ${calcCH(v,"bald")} · Bright's ${calcCH(v,"brights")}`})}
function setAdminTab(which){document.querySelectorAll(".admintabs button").forEach(b=>b.classList.toggle("on",b.dataset.tab===which));if(which==="pairings"){renderAdminPairings();saveAdmin.textContent="Save pairings";saveAdmin.dataset.mode="pairings"}else{renderAdminHandicaps();saveAdmin.textContent="Save handicaps";saveAdmin.dataset.mode="handicaps"}}
function openAdmin(){if(sessionStorage.getItem("ll-admin-ok")!=="1"){let pin=prompt("Enter Admin PIN");if(pin!==ADMIN_PIN){if(pin!==null)alert("Incorrect PIN.");return}sessionStorage.setItem("ll-admin-ok","1")}modal.classList.add("on");setAdminTab("pairings")}
document.getElementById("admin").onclick=openAdmin;document.getElementById("close").onclick=()=>modal.classList.remove("on");modal.addEventListener("click",e=>{if(e.target===modal)modal.classList.remove("on")});document.addEventListener("keydown",e=>{if(e.key==="Escape"){modal.classList.remove("on");scorecard.classList.remove("on")}});
saveAdmin.onclick=async()=>{if(saveAdmin.dataset.mode==="handicaps"){let bad=false;document.querySelectorAll(".handicaprow").forEach(row=>{let v=parseFloat(row.querySelector(".hindex").value),p=P(row.dataset.p);if(Number.isNaN(v)){bad=true;return}p.index=v;p.apple=calcCH(v,"apple");p.bald=calcCH(v,"bald");p.brights=calcCH(v,"brights")});if(bad)return alert("Every listed player needs a valid index.");saveHandicapSnapshot();modal.classList.remove("on");render();alert("2026 handicap snapshot saved on this device.");return}let rows=[];document.querySelectorAll(".adminmatch").forEach(e=>{let m=M.find(x=>x.id===e.dataset.id),a=[],b=[];e.querySelectorAll("select").forEach(s=>{if(s.value)(s.dataset.s==="a"?a:b)[+s.dataset.i]=s.value});m.a=a.filter(Boolean);m.b=b.filter(Boolean);rows.push({id:m.id,event_id:"lake-lure-2026",round_no:m.round,course_id:m.course,format:m.format,team_a:m.a,team_b:m.b,points:m.points,status:"scheduled"})});let {error}=await sb.from("matches").upsert(rows);if(error)return alert(error.message);modal.classList.remove("on");render()}
async function load(){try{let [a,b,c]=await Promise.all([sb.from("matches").select("*").eq("event_id","lake-lure-2026"),sb.from("hole_scores").select("*"),sb.from("team_hole_scores").select("*")]);if(a.error||b.error||c.error)throw(a.error||b.error||c.error);a.data?.forEach(r=>{let m=M.find(x=>x.id===r.id);if(m){m.a=r.team_a||[];m.b=r.team_b||[]}});b.data?.forEach(r=>S[`${r.match_id}:${r.hole}:${r.player_id}`]=r.gross);c.data?.forEach(r=>S[`${r.match_id}:${r.hole}:${r.team}`]=r.gross);sync.textContent="● Supabase connected";render()}catch(e){sync.textContent="Setup error: "+e.message}}
function startIntro(){if(localStorage.getItem("ll-intro-seen-8"))return;intro.classList.add("on");localStorage.setItem("ll-intro-seen-8","1");setTimeout(()=>intro.classList.remove("on"),2350)}skipIntro.onclick=()=>intro.classList.remove("on");skipRound.onclick=()=>roundIntro.classList.remove("on");render();showView(localStorage.getItem(LS.view)||"cup");startIntro();load();sb.channel("live").on("postgres_changes",{event:"*",schema:"public",table:"hole_scores"},load).on("postgres_changes",{event:"*",schema:"public",table:"team_hole_scores"},load).on("postgres_changes",{event:"*",schema:"public",table:"matches"},load).subscribe();